---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: This is a new road content
  label: Test 1 (Label)
  create: all
  match: "**/*"
  new_doc_ext: test1.md
  templates:
  - deneme
upload_dir: public/static
public_path: public/static
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
